version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  api:
    build: ./api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/cards_db
    ports:
      - "8000:8000"
  bot:
    build: ./bot
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
